#!/bin/sh
## DESCRIPTION=This script created by Levi45\nKeys Uodater
###############################################################################
SoftcamKeys="http://levi45.spdns.eu/Addons/SoftCam.Key"
echo ""
echo ""
echo "Downloading ${SoftcamKeys}"
wget ${SoftcamKeys} -O /usr/keys/SoftCam.Key || echo "Error: Couldn't connect to ${SoftcamKeys}"
echo ""
echo "Downloading ${SoftcamKeys}"
wget ${SoftcamKeys} -O /etc/tuxbox/config/SoftCam.Key || echo "Error: Couldn't connect to ${SoftcamKeys}"
echo ""
echo ""
echo "#########################################################"
echo "#                           Levi45                      #"
echo "#########################################################"
echo "#              KEYS INSTALLED SUCCESSFULLY              #"
echo "#########################################################"
echo "#                    SATELLITE-FORUM.COM                #"
echo "#########################################################"
KeyDate=`/bin/date -r /usr/keys/SoftCam.Key +%d.%m.%y-%H:%M:%S`
	echo ""
	echo "UPDATE DATE AND TIME: $KeyDate"
exit 0
